# Generated by Django 2.2 on 2020-04-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Spine'), ('SW', 'Trauma'), ('OW', 'Arthroplasty')], max_length=2),
        ),
    ]
